### PR TITLE
Fix issue where Newtonsoft conflicts with default packages.

### PR DESCRIPTION
**Pull request by Spillmaker**
Not sure when Unity started doing it, but in my use-case (2D project, Unity 2021.3.4f1 on Mac) there is already a Newtonsoft package included as an dependency for the 2D base package. Making it impossible to use this package since you cant have multiple DLL-files with the same package name.

I removed the DLL-files and included Newtonsoft as a dependency.

Initial testing for my usecases seems to work fine, but since i dont know this codebase i cant be 100% sure that this will work in all scenarios.

### CODE REVIEW

**Comment by itisnajim** [comment]
Maybe i have to put all possible libraries to package.json dependencies property instead,
what you provide `"nuget.newtonsoft-json" : "3.0.2"` is a one

**Comment by Spillmaker** [comment]
Think that would be beneficial yea, but some libraries may not be available, so you would have to check that first.

This is a good start on that progress tho.

**Comment by didix16** [comment]
Any news about merging PR? Thanks

**Comment by OlliePugh** [comment]
Would be great to see this get merged, worked perfectly for me 👍

**Comment by sumitprof2017** [comment]
i have multiple assemblies problem with json.net how can i fix this please help?

**Pull request merged**
